// code/ig-clone/ig-clone-angular/src/app/create/create.component.ts
import { Component } from '@angular/core';
import { RouterLink } from '@angular/router';
import { NotInstagramLogoComponent } from '../components/not-instagram-logo/not-instagram-logo.component';
import { XIconComponent } from '../components/icons/xicon/xicon.component';
import { PostComponent } from '../components/post/post.component';
import { NgFor } from '@angular/common';
import { FormsModule } from '@angular/forms';

@Component({
  selector: 'app-create',
  standalone: true,
  imports: [RouterLink, NotInstagramLogoComponent, XIconComponent, PostComponent, NgFor, FormsModule],
  templateUrl: './create.component.html',
  styleUrl: './create.component.css'
})
export class CreateComponent {
  preloadedMedia: string[] = [
    "canyon.mp4",
    "easter-bunnies.mp4",
    "reading.mp4",
    "skaters.mp4",
    "abstract-circles.jpg",
    "joseph-joker.jpg",
    "asian-house.jpg",
    "lars-local.jpg",
    "backpack.jpg",
    "moon.jpg",
    "beach.mp4",
    "beach.jpg",
    "mountains.jpg",
    "bernd-bart.jpg",
    "peter-poster.jpg",
    "busy-street.jpg",
    "rosa-rot.jpg",
    "couple-kitchen.jpg",
    "snow-mountains.jpg",
    "donna-drama.jpg",
    "steffi-sanft.jpg",
    "dramatic-portrait.jpg",
    "steffi-sauer.jpg",
    "elsa-erdbeere.jpg",
    "surfer.jpg",
    "field-wheat.jpg",
    "tina-traveller.jpg",
    "filippa-feurig.jpg",
    "tokio-trees.jpg",
    "flower-art.jpg",
    "wave.jpg",
    "gabriela-gut.jpg",
    "wild-sea.jpg",
    "garden-art.jpg",
    "your-profile.jpg",
  ]
  userhandle: string = "@you"
  caption: string = ""
  mediaUrl: string = ""
  mediaChoice: string = ""

  mediaSource(): string {
    if (this.mediaUrl) return this.mediaUrl;
    return this.mediaChoice;
  }
}

<header>
  <a [routerLink]="['/']" routerLinkActive="router-link-active">
    <app-not-instagram-logo />
  </a>
  <a [routerLink]="['/']" routerLinkActive="router-link-active">
    <app-xicon />
  </a>
</header>

<form id="newPostForm" action="" method="post">
  <input
    [(ngModel)]="mediaUrl"
    type="url"
    name="mediaUrl"
    id="mediaUrl"
    placeholder="Insert your media URL here..."
  />
  <p>or</p>
  <select name="preloaded-image" id="preloaded-image" [(ngModel)]="mediaChoice">
    <option value="">Choose one of our media files here...</option>
    <option *ngFor="let media of preloadedMedia" [value]="media">
      <span> {{ media }} </span>
    </option>
  </select>
  <textarea
    [(ngModel)]="caption"
    name="caption"
    id="caption"
    cols="30"
    rows="3"
    placeholder="Type your caption here"
  ></textarea>
  <button type="submit" [disabled]="!(caption && mediaSource)">Post it!</button>
</form>

<hr />

<app-post
  [userhandle]="userhandle"
  [caption]="caption"
  [likeCount]="0"
  [mediaSource]="mediaUrl || mediaChoice"
  [hideActionIcons]="true"
/>

// code/ig-clone/ig-clone-next/src/app/create/page.tsx
"use client";

import Link from "next/link";
import styles from "./create.module.css";
import NotInstagramLogo from "@/components/NotInstagramLogo";
import Post from "@/components/Post";
// import Post from "@/components/Post";
import XIcon from "@/components/icons/XIcon";
import { useEffect, useState } from "react";

const preloadedMedia = [
  "canyon.mp4",
  "easter-bunnies.mp4",
  "reading.mp4",
  "skaters.mp4",
  "abstract-circles.jpg",
  "joseph-joker.jpg",
  "asian-house.jpg",
  "lars-local.jpg",
  "backpack.jpg",
  "moon.jpg",
  "beach.mp4",
  "beach.jpg",
  "mountains.jpg",
  "bernd-bart.jpg",
  "peter-poster.jpg",
  "busy-street.jpg",
  "rosa-rot.jpg",
  "couple-kitchen.jpg",
  "snow-mountains.jpg",
  "donna-drama.jpg",
  "steffi-sanft.jpg",
  "dramatic-portrait.jpg",
  "steffi-sauer.jpg",
  "elsa-erdbeere.jpg",
  "surfer.jpg",
  "field-wheat.jpg",
  "tina-traveller.jpg",
  "filippa-feurig.jpg",
  "tokio-trees.jpg",
  "flower-art.jpg",
  "wave.jpg",
  "gabriela-gut.jpg",
  "wild-sea.jpg",
  "garden-art.jpg",
  "your-profile.jpg",
];

const userhandle = "@you";

const CreatePost = () => {
  const [caption, setCaption] = useState("");
  const [mediaUrl, setmediaUrl] = useState("");
  const [mediaChoice, setmediaChoice] = useState("");
  const [mediaSource, setMediaSource] = useState(mediaChoice);

  useEffect(() => {
    setMediaSource(mediaUrl || mediaChoice);
  });
  // function mediaSource() {
  //   return mediaUrl || mediaChoice;
  // }

  return (
    <>
      <header className={styles.createHeader}>
        <Link href="/">
          <NotInstagramLogo />
        </Link>
        <Link href="/">
          <XIcon />
        </Link>
      </header>

      <form id={styles.newPostForm} action="" method="post">
        <input
          type="url"
          name="mediaUrl"
          id={styles.mediaUrl}
          placeholder="Insert your media URL here..."
          value={mediaUrl}
          onChange={(event) => setmediaUrl(event.target.value)}
        />
        <p>or</p>
        <select
          name="preloaded-image"
          id={styles["preloadedimage"]}
          value={mediaChoice}
          onChange={(event) => setmediaChoice(event.target.value)}
        >
          <option value="">Choose one of our media files here...</option>
          {preloadedMedia.map((media) => (
            <option key={media} value={media}>
              {media}
            </option>
          ))}
        </select>
        <textarea
          name="caption"
          id={styles.caption}
          cols={30}
          rows={3}
          placeholder="Type your caption here"
          value={caption}
          onChange={(event) => setCaption(event.target.value)}
        ></textarea>
        <button type="submit" disabled={!(caption && mediaSource)}>
          Post it!
        </button>
      </form>

      <hr />

      <Post
        userhandle={userhandle}
        caption={caption}
        likeCount={0}
        mediaSource={mediaSource}
        hideActionIcons={true}
      />
    </>
  );
};

export default CreatePost;
