// code/ig-clone/ig-clone-nuxt/components/MediaComponent.vue
<script setup>
// const glob = import.meta.glob("~/assets/stock-footage/*", { eager: true });
// const media = Object.fromEntries(
//   Object.entries(glob).map(([key, value]) => [
//     key.split("/")[key.split("/").length - 1],
//     value.default,
//   ])
// );
</script>

<template>
  <img
    class="postMedia"
    v-if="mediaSource?.endsWith('jpg')"
    :src="mediaSource"
    :alt="alt"
    :width="width"
    :height="height"
  />
  <video
    class="postMedia"
    v-else-if="mediaSource?.endsWith('mp4')"
    :width="width"
    autoplay="true"
    controls
    controlslist="nodownload,nofullscreen,noremoteplayback"
    disablepictureinpicture
    loop
    muted
  >
    <source :src="mediaSource" type="video/mp4" />
  </video>
  <div v-else class="mediaError">
    <p>Nothing to see yet...<br />Choose an image to continue!</p>
  </div>
</template>

<script>
const glob = import.meta.glob("~/assets/stock-footage/*", { eager: true });
const media = Object.fromEntries(
  Object.entries(glob).map(([key, value]) => [
    key.split("/")[key.split("/").length - 1],
    value.default,
  ])
);

export default {
  name: "MediaComponent",
  props: {
    src: {
      type: String,
    },
    alt: {
      type: String,
      default: "",
    },
    width: String,
    height: String,
  },
  computed: {
    mediaSource() {
      return this.src == null ||
        this.src == undefined ||
        this.src.startsWith("http")
        ? this.src
        : media[this.src];
    },
  },
};
</script>

<style>
.mediaError {
  display: grid;
  place-items: center;
  text-align: center;

  background-color: #d9d9d9;
  min-height: 300px;
  width: 100%;
}

.mediaError p {
  font-size: 14px;
}

.postMedia {
  aspect-ratio: 1 / 1;
  object-fit: cover;
}
</style>

// code/ig-clone/ig-clone-astro/src/components/MediaComponent.jsx
import { useEffect, useState } from "react";
import styles from "./MediaComponent.module.css";

const mediaFiles = import.meta.glob("/src/assets/stock-footage/*.{jpg,mp4}");
const media = Object.fromEntries(
  Object.entries(mediaFiles).map(([key, value]) => [
    key.split("/")[key.split("/").length - 1],
    value,
  ])
);

const MediaComponent = (props) => {
  const { src, alt, width, height, className, id, ...rest } = props;
  const [mediaSource, setMediaSource] = useState("");

  useEffect(() => {
    if (src?.startsWith("http")) setMediaSource(src);
    else if (src)
      media[src]().then((mediaFile) => {
        if (src.endsWith("jpg")) setMediaSource(mediaFile.default.src);
        else setMediaSource(mediaFile.default);
      });
  });

  if (mediaSource && src?.endsWith("jpg"))
    return (
      <img
        key={src}
        src={mediaSource}
        alt={alt}
        width={width}
        height={height}
        className={[className, styles.postMedia].join(" ")}
        id={id}
        {...rest}
      />
    );
  else if (mediaSource && src.endsWith("mp4"))
    return (
      <video
        key={mediaSource}
        className={[className, styles.postMedia].join(" ")}
        id={id}
        width={width}
        autoPlay={true}
        controls
        controlsList="nodownload,nofullscreen,noremoteplayback"
        disablePictureInPicture
        loop
        muted
      >
        <source src={mediaSource} type="video/mp4" />
      </video>
    );
  // else if (!mediaSource)
  //   return (
  //     <div
  //       {...rest}
  //       className={[className, styles.postMedia].join(" ")}
  //       style={{ width: width + "px" }}
  //     ></div>
  //   );
  else
    return (
      <div className={styles.mediaError}>
        <p>
          Nothing to see yet...
          <br />
          Choose an image to continue!
        </p>
      </div>
    );
};

export default MediaComponent;
