// code/ig-clone/ig-clone-angular/src/app/components/media-component/media-component.component.ts
import { NgIf } from '@angular/common';
import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-media-component',
  standalone: true,
  imports: [NgIf],
  templateUrl: './media-component.component.html',
  styleUrl: './media-component.component.css'
})
export class MediaComponentComponent {
  @Input() src!: string;
  @Input() alt: string = "";
  @Input() width?: string;
  @Input() height?: string;
  @Input() id?: string;
  @Input() class?: string;

  mediaSource: string = "";


  constructor() { }

  ngOnChanges(): void {
    if (
      this.src == null ||
      this.src == undefined ||
      this.src.startsWith("http")
    )
      this.mediaSource = this.src;

    else this.mediaSource = `assets/stock-footage/${this.src}`
  }

}

<img
  class="postMedia"
  *ngIf="mediaSource && mediaSource.endsWith('jpg'); else videoMedia"
  [src]="mediaSource"
  [alt]="alt"
  [attr.width]="width"
  [attr.height]="height"
  [id]="id"
  [class]="class"
/>
<ng-template #videoMedia>
  <video
    class="postMedia"
    *ngIf="mediaSource && mediaSource.endsWith('mp4'); else mediaError"
    [attr.width]="width"
    autoplay="true"
    controls
    controlslist="nodownload,nofullscreen,noremoteplayback"
    disablepictureinpicture
    loop
    [muted]="true"
  >
    <source [src]="mediaSource" type="video/mp4" />
  </video>
</ng-template>
<ng-template #mediaError>
  <div class="mediaError">
    <p>Nothing to see yet...<br />Choose an image to continue!</p>
  </div>
</ng-template>

// code/ig-clone/ig-clone-react/src/components/MediaComponent.js
import styles from "./MediaComponent.module.css"

const MediaComponent = ({ src, alt, width, height, className, id }) => {
  let mediaSource = ""

  try {
    mediaSource = src.startsWith('http') ? src : require(`src/assets/stock-footage/${src}`)
  } catch (error) {
    mediaSource = ""
  }

  if (mediaSource.endsWith('jpg')) return <img src={mediaSource} alt={alt} width={width} height={height} className={[className, styles.postMedia].join(" ")} id={id} />
  else if (mediaSource.endsWith('mp4')) return (
    <video
      className={[className, styles.postMedia].join(" ")}
      id={id}
      width={width}
      autoPlay={true}
      controls
      controlsList="nodownload,nofullscreen,noremoteplayback"
      disablePictureInPicture
      loop
      muted
    >
      <source src={mediaSource} type="video/mp4" />
    </video>
  )
  else return (
    <div className={styles.mediaError}>
      <p>Nothing to see yet...<br />Choose an image to continue!</p>
    </div>)
}

export default MediaComponent
