// code/ig-clone/ig-clone-angular/src/app/components/profile-list/profile-list.component.ts
import { Component, Input } from '@angular/core';
import { RouterLink } from '@angular/router';
import { MediaComponentComponent } from '../media-component/media-component.component';
import { NgFor } from '@angular/common';

@Component({
  selector: 'app-profile-list',
  standalone: true,
  imports: [RouterLink, MediaComponentComponent, NgFor],
  templateUrl: './profile-list.component.html',
  styleUrl: './profile-list.component.css'
})
export class ProfileListComponent {
  @Input() profiles!: Array<any>
}

<div id="profileList">
  <a
    [routerLink]="['/user/' + profile.handle]"
    routerLinkActive="router-link-active"
    class="profileListItem"
    *ngFor="let profile of profiles"
  >
    <app-media-component
      class="profileImage"
      [src]="profile.profileImageSource"
      [alt]="profile.handle"
      width="91"
      height="91"
    />
    <p class="username">{{ profile.username }}</p>
  </a>
</div>

// code/ig-clone/ig-clone-react/src/components/ProfileList.js
import { Link } from "react-router-dom"
import styles from "./ProfileList.module.css"
import MediaComponent from "./MediaComponent"


const ProfileList = ({ profiles }) => {

  return <div id={styles.profileList}>
    {profiles.map(profile =>
      <Link to={"/user/" + profile.handle}
        className={styles.profileListItem}
        key={profile.handle}
      >
        <MediaComponent
          className={styles.profileImage}
          src={profile.profileImageSource}
          alt={profile.handle}
          width="91"
          height="91"
        />
        <p className={styles.username}>{profile.username}</p>
      </Link>
    )}
  </div >
}

export default ProfileList
