// code/ig-clone/ig-clone-vue/src/components/ProfileList.vue
<script setup>
import MediaComponent from "@/components/MediaComponent.vue";
</script>

<template>
  <div id="profileList">
    <RouterLink
      :to="{ name: 'Profile', params: { handle: profile.handle } }"
      class="profileListItem"
      v-for="profile in profiles"
      :key="profile.handle"
    >
      <MediaComponent
        class="profileImage"
        :src="profile.profileImageSource"
        :alt="profile.handle"
        width="91"
        height="91"
      />
      <p class="username">{{ profile.username }}</p>
    </RouterLink>
  </div>
</template>

<script>
export default {
  name: "ProfileList",
  props: {
    profiles: Array,
  },
};
</script>

<style scoped>
#profileList {
  margin: 8px 0;
  padding: 0 16px;
  display: flex;
  flex-wrap: nowrap;
  overflow-x: auto;
  -ms-overflow-style: none;
  scrollbar-width: none;
}

#profileList::-webkit-scrollbar {
  display: none;
}

.profileListItem {
  display: flex;
  flex-direction: column;
  justify-content: center;
  align-items: center;
  text-align: center;
  margin-right: 16px;
  color: inherit;
  text-decoration: inherit;
}

.profileListItem:last-of-type {
  margin-right: 0;
}

.profileImage {
  border-radius: 50%;
}

.username {
  white-space: nowrap;
}
</style>

// code/ig-clone/ig-clone-react/src/components/ProfileList.js
import { Link } from "react-router-dom"
import styles from "./ProfileList.module.css"
import MediaComponent from "./MediaComponent"


const ProfileList = ({ profiles }) => {

  return <div id={styles.profileList}>
    {profiles.map(profile =>
      <Link to={"/user/" + profile.handle}
        className={styles.profileListItem}
        key={profile.handle}
      >
        <MediaComponent
          className={styles.profileImage}
          src={profile.profileImageSource}
          alt={profile.handle}
          width="91"
          height="91"
        />
        <p className={styles.username}>{profile.username}</p>
      </Link>
    )}
  </div >
}

export default ProfileList
