// code/ig-clone/ig-clone-nuxt/components/PostList.vue
<template>
  <div id="postList">
    <Post
      v-for="post in posts"
      :userhandle="post.userhandle"
      :caption="post.caption"
      :mediaSource="post.mediaSource"
      :likeCount="post.likeCount"
      :createdAt="post.createdAt"
    />
  </div>
</template>

<script>
export default {
  name: "PostList",
  props: {
    posts: Array,
  },
};
</script>

<style></style>

// code/ig-clone/ig-clone-angular/src/app/components/post-list/post-list.component.ts
import { Component, Input } from '@angular/core';
import { PostComponent } from '../post/post.component';
import { NgFor } from '@angular/common';

@Component({
  selector: 'app-post-list',
  standalone: true,
  imports: [PostComponent, NgFor],
  templateUrl: './post-list.component.html',
  styleUrl: './post-list.component.css'
})
export class PostListComponent {
  @Input() posts!: Array<any>
}

<div id="postList">
  <app-post
    *ngFor="let post of posts"
    [userhandle]="post.userhandle"
    [caption]="post.caption"
    [mediaSource]="post.mediaSource"
    [likeCount]="post.likeCount"
    [createdAt]="post.createdAt"
  />
</div>
