// code/ig-clone/ig-clone-angular/src/app/about/about.component.ts
import { Component } from '@angular/core';
import { NotInstagramLogoComponent } from '../components/not-instagram-logo/not-instagram-logo.component';
import { SendIconComponent } from '../components/icons/send-icon/send-icon.component';
import { InfoBlockComponent } from '../components/info-block/info-block.component';
import { RouterLink } from '@angular/router';

@Component({
  selector: 'app-about',
  standalone: true,
  imports: [NotInstagramLogoComponent, SendIconComponent, InfoBlockComponent, RouterLink],
  templateUrl: './about.component.html',
  styleUrl: './about.component.css'
})
export class AboutComponent {

}

<div id="AboutView">
  <a
    [routerLink]="['/']"
    routerLinkActive="router-link-active"
    id="top-backlink"
    class="backlink"
  >
    back
  </a>

  <p class="cursive">This is</p>
  <app-not-instagram-logo />
  <img class="transparent logo" src="assets/logo.svg" alt="" width="40%" />

  <p class="cursive">created by</p>
  <p class="cursive big">Andreas Nicklaus</p>
  <div id="socials">
    <p>
      <a href="https://github.com/andreasnicklaus" target="_blank">
        <img class="transparent" src="assets/github.svg" width="29" />
        &#64;andreasnicklaus
      </a>
    </p>
    <p>
      <a href="https://www.linkedin.com/in/andreasnicklaus/" target="_blank">
        <img class="transparent" src="assets/linkedin.svg" width="29" />
        &#64;andreasnicklaus
      </a>
    </p>
    <p>
      <a href="mailto:an067@hdm-stuttgart.de">
        <app-send-icon />
        an067&#64;hdm-stuttgart.de
      </a>
    </p>
  </div>

  <app-info-block title="What is this?">
    This project is part of the master thesis by Andreas Nicklaus with a working
    title. The following are just placholder texts.
  </app-info-block>
  <app-info-block title="Placeholder 1">
    Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod
    tempor incididunt ut labore et dolore magna aliqua. Elementum curabitur
    vitae nunc sed velit. Sagittis vitae et leo duis. Facilisi morbi tempus
    iaculis urna id volutpat lacus. Pellentesque id nibh tortor id aliquet
    lectus. Nisi quis eleifend quam adipiscing. Convallis a cras semper auctor
    neque vitae tempus quam. Pulvinar neque laoreet suspendisse interdum
    consectetur libero id faucibus. Facilisis sed odio morbi quis. Porttitor
    massa id neque aliquam vestibulum morbi blandit cursus. Lacus vestibulum sed
    arcu non odio euismod lacinia at. Sagittis eu volutpat odio facilisis mauris
    sit amet. Felis eget velit aliquet sagittis id consectetur purus. Sapien
    pellentesque habitant morbi tristique. Faucibus purus in massa tempor nec
    feugiat nisl. Lacus sed viverra tellus in hac. Mauris pellentesque pulvinar
    pellentesque habitant morbi tristique senectus. Rhoncus urna neque viverra
    justo nec. Amet cursus sit amet dictum sit amet justo donec enim. Sed libero
    enim sed faucibus turpis in.
  </app-info-block>
  <app-info-block title="Placeholder 2">
    Pellentesque diam volutpat commodo sed egestas egestas fringilla phasellus.
    Vulputate odio ut enim blandit. A condimentum vitae sapien pellentesque. Eu
    feugiat pretium nibh ipsum consequat nisl vel pretium. Feugiat nibh sed
    pulvinar proin gravida. Arcu non sodales neque sodales ut etiam sit amet.
    Amet risus nullam eget felis eget nunc lobortis. Diam vel quam elementum
    pulvinar etiam non quam lacus. Tincidunt id aliquet risus feugiat. Curabitur
    gravida arcu ac tortor dignissim convallis aenean. Cras fermentum odio eu
    feugiat pretium. Lacinia quis vel eros donec ac odio tempor. Eu turpis
    egestas pretium aenean pharetra.
  </app-info-block>
  <app-info-block title="Placeholder 3">
    Nec feugiat nisl pretium fusce. Sagittis id consectetur purus ut faucibus
    pulvinar elementum integer. Fusce id velit ut tortor. Enim blandit volutpat
    maecenas volutpat blandit aliquam etiam erat. Morbi quis commodo odio aenean
    sed adipiscing. Ut consequat semper viverra nam. Quisque egestas diam in
    arcu cursus euismod quis. Nec feugiat in fermentum posuere urna nec
    tincidunt. Ut lectus arcu bibendum at varius vel pharetra vel turpis.
    Tincidunt id aliquet risus feugiat. Id donec ultrices tincidunt arcu non
    sodales neque sodales. Vitae justo eget magna fermentum iaculis eu.
    Pellentesque habitant morbi tristique senectus et netus et. Sit amet
    consectetur adipiscing elit ut aliquam purus.
  </app-info-block>
  <app-info-block title="Placeholder 4">
    Ullamcorper malesuada proin libero nunc. Netus et malesuada fames ac turpis
    egestas. Aenean vel elit scelerisque mauris pellentesque pulvinar
    pellentesque. In iaculis nunc sed augue lacus viverra vitae congue. Pharetra
    sit amet aliquam id diam maecenas ultricies mi. Feugiat in fermentum posuere
    urna nec tincidunt praesent. Sollicitudin ac orci phasellus egestas tellus
    rutrum tellus pellentesque. Cursus vitae congue mauris rhoncus aenean vel
    elit scelerisque mauris. Fringilla phasellus faucibus scelerisque eleifend
    donec pretium vulputate sapien nec. Cursus eget nunc scelerisque viverra
    mauris in aliquam. Tellus orci ac auctor augue mauris. Ac orci phasellus
    egestas tellus rutrum tellus pellentesque eu. Consequat semper viverra nam
    libero justo laoreet sit amet. Mauris cursus mattis molestie a. Risus
    commodo viverra maecenas accumsan. Pretium lectus quam id leo in vitae
    turpis. Viverra tellus in hac habitasse platea dictumst. Cras pulvinar
    mattis nunc sed blandit libero volutpat. Ut faucibus pulvinar elementum
    integer enim neque volutpat. Orci a scelerisque purus semper eget duis at.
  </app-info-block>
  <app-info-block title="Placeholder 5">
    Adipiscing elit pellentesque habitant morbi tristique. Nulla at volutpat
    diam ut venenatis tellus in metus vulputate. Tortor consequat id porta nibh
    venenatis cras. Hac habitasse platea dictumst vestibulum. Arcu cursus vitae
    congue mauris rhoncus aenean vel elit. Erat pellentesque adipiscing commodo
    elit. Odio ut enim blandit volutpat maecenas volutpat blandit aliquam etiam.
    Semper viverra nam libero justo laoreet sit amet cursus. Semper eget duis at
    tellus at urna condimentum mattis pellentesque. Sed cras ornare arcu dui
    vivamus arcu felis. Vitae tortor condimentum lacinia quis vel eros donec ac.
    Vitae aliquet nec ullamcorper sit amet risus nullam. Pharetra massa massa
    ultricies mi. Cursus eget nunc scelerisque viverra mauris in aliquam sem
    fringilla. In massa tempor nec feugiat nisl pretium. Ultrices eros in cursus
    turpis massa tincidunt dui ut. Integer quis auctor elit sed. Ultricies
    integer quis auctor elit. Ridiculus mus mauris vitae ultricies leo integer
    malesuada nunc vel.
  </app-info-block>
  <a
    [routerLink]="['/']"
    routerLinkActive="router-link-active"
    id="bottom-backlink"
    class="backlink"
  >
    back
  </a>
</div>

// code/ig-clone/ig-clone-next/src/app/about/page.tsx
import Image from "next/image";
import Link from "next/link";

import styles from "./About.module.css";
import NotInstagramLogo from "@/components/NotInstagramLogo";
import SendIcon from "@/components/icons/SendIcon";
import Logo from "@/assets/logo.svg";
import Github from "@/assets/github.svg";
import LinkedIn from "@/assets/linkedin.svg";
import InfoBlock from "@/components/InfoBlock";

import { Kaushan_Script } from "next/font/google";
const kaushanScript = Kaushan_Script({ subsets: ["latin"], weight: "400" });

const About = () => {
  return (
    <div id={styles.AboutView}>
      <Link id={styles["top-backlink"]} className={styles.backlink} href="/">
        back
      </Link>

      <p className={[styles.cursive, kaushanScript.className].join(" ")}>
        This is
      </p>
      <NotInstagramLogo />
      <Image
        className={styles.logo + " transparent"}
        src={Logo}
        alt=""
        sizes="40%"
      />

      <p className={[styles.cursive, kaushanScript.className].join(" ")}>
        created by
      </p>
      <p
        className={[styles.cursive, styles.big, kaushanScript.className].join(
          " "
        )}
      >
        Andreas Nicklaus
      </p>
      <div id={styles.socials}>
        <p>
          <a href="https://github.com/andreasnicklaus" target="_blank">
            <Image className="transparent" src={Github} width="29" alt="" />
            @andreasnicklaus
          </a>
        </p>
        <p>
          <a
            href="https://www.linkedin.com/in/andreasnicklaus/"
            target="_blank"
          >
            <Image className="transparent" src={LinkedIn} width="29" alt="" />
            @andreasnicklaus
          </a>
        </p>
        <p>
          <a href="mailto:an067@hdm-stuttgart.de">
            <SendIcon />
            an067@hdm-stuttgart.de
          </a>
        </p>
      </div>

      <InfoBlock title="What is this?">
        This project is part of the master thesis by Andreas Nicklaus with a
        working title. The following are just placholder texts.
      </InfoBlock>
      <InfoBlock title="Placeholder 1">
        Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod
        tempor incididunt ut labore et dolore magna aliqua. Elementum curabitur
        vitae nunc sed velit. Sagittis vitae et leo duis. Facilisi morbi tempus
        iaculis urna id volutpat lacus. Pellentesque id nibh tortor id aliquet
        lectus. Nisi quis eleifend quam adipiscing. Convallis a cras semper
        auctor neque vitae tempus quam. Pulvinar neque laoreet suspendisse
        interdum consectetur libero id faucibus. Facilisis sed odio morbi quis.
        Porttitor massa id neque aliquam vestibulum morbi blandit cursus. Lacus
        vestibulum sed arcu non odio euismod lacinia at. Sagittis eu volutpat
        odio facilisis mauris sit amet. Felis eget velit aliquet sagittis id
        consectetur purus. Sapien pellentesque habitant morbi tristique.
        Faucibus purus in massa tempor nec feugiat nisl. Lacus sed viverra
        tellus in hac. Mauris pellentesque pulvinar pellentesque habitant morbi
        tristique senectus. Rhoncus urna neque viverra justo nec. Amet cursus
        sit amet dictum sit amet justo donec enim. Sed libero enim sed faucibus
        turpis in.
      </InfoBlock>
      <InfoBlock title="Placeholder 2">
        Pellentesque diam volutpat commodo sed egestas egestas fringilla
        phasellus. Vulputate odio ut enim blandit. A condimentum vitae sapien
        pellentesque. Eu feugiat pretium nibh ipsum consequat nisl vel pretium.
        Feugiat nibh sed pulvinar proin gravida. Arcu non sodales neque sodales
        ut etiam sit amet. Amet risus nullam eget felis eget nunc lobortis. Diam
        vel quam elementum pulvinar etiam non quam lacus. Tincidunt id aliquet
        risus feugiat. Curabitur gravida arcu ac tortor dignissim convallis
        aenean. Cras fermentum odio eu feugiat pretium. Lacinia quis vel eros
        donec ac odio tempor. Eu turpis egestas pretium aenean pharetra.
      </InfoBlock>
      <InfoBlock title="Placeholder 3">
        Nec feugiat nisl pretium fusce. Sagittis id consectetur purus ut
        faucibus pulvinar elementum integer. Fusce id velit ut tortor. Enim
        blandit volutpat maecenas volutpat blandit aliquam etiam erat. Morbi
        quis commodo odio aenean sed adipiscing. Ut consequat semper viverra
        nam. Quisque egestas diam in arcu cursus euismod quis. Nec feugiat in
        fermentum posuere urna nec tincidunt. Ut lectus arcu bibendum at varius
        vel pharetra vel turpis. Tincidunt id aliquet risus feugiat. Id donec
        ultrices tincidunt arcu non sodales neque sodales. Vitae justo eget
        magna fermentum iaculis eu. Pellentesque habitant morbi tristique
        senectus et netus et. Sit amet consectetur adipiscing elit ut aliquam
        purus.
      </InfoBlock>
      <InfoBlock title="Placeholder 4">
        Ullamcorper malesuada proin libero nunc. Netus et malesuada fames ac
        turpis egestas. Aenean vel elit scelerisque mauris pellentesque pulvinar
        pellentesque. In iaculis nunc sed augue lacus viverra vitae congue.
        Pharetra sit amet aliquam id diam maecenas ultricies mi. Feugiat in
        fermentum posuere urna nec tincidunt praesent. Sollicitudin ac orci
        phasellus egestas tellus rutrum tellus pellentesque. Cursus vitae congue
        mauris rhoncus aenean vel elit scelerisque mauris. Fringilla phasellus
        faucibus scelerisque eleifend donec pretium vulputate sapien nec. Cursus
        eget nunc scelerisque viverra mauris in aliquam. Tellus orci ac auctor
        augue mauris. Ac orci phasellus egestas tellus rutrum tellus
        pellentesque eu. Consequat semper viverra nam libero justo laoreet sit
        amet. Mauris cursus mattis molestie a. Risus commodo viverra maecenas
        accumsan. Pretium lectus quam id leo in vitae turpis. Viverra tellus in
        hac habitasse platea dictumst. Cras pulvinar mattis nunc sed blandit
        libero volutpat. Ut faucibus pulvinar elementum integer enim neque
        volutpat. Orci a scelerisque purus semper eget duis at.
      </InfoBlock>
      <InfoBlock title="Placeholder 5">
        Adipiscing elit pellentesque habitant morbi tristique. Nulla at volutpat
        diam ut venenatis tellus in metus vulputate. Tortor consequat id porta
        nibh venenatis cras. Hac habitasse platea dictumst vestibulum. Arcu
        cursus vitae congue mauris rhoncus aenean vel elit. Erat pellentesque
        adipiscing commodo elit. Odio ut enim blandit volutpat maecenas volutpat
        blandit aliquam etiam. Semper viverra nam libero justo laoreet sit amet
        cursus. Semper eget duis at tellus at urna condimentum mattis
        pellentesque. Sed cras ornare arcu dui vivamus arcu felis. Vitae tortor
        condimentum lacinia quis vel eros donec ac. Vitae aliquet nec
        ullamcorper sit amet risus nullam. Pharetra massa massa ultricies mi.
        Cursus eget nunc scelerisque viverra mauris in aliquam sem fringilla. In
        massa tempor nec feugiat nisl pretium. Ultrices eros in cursus turpis
        massa tincidunt dui ut. Integer quis auctor elit sed. Ultricies integer
        quis auctor elit. Ridiculus mus mauris vitae ultricies leo integer
        malesuada nunc vel.
      </InfoBlock>
      <Link id={styles["bottom-backlink"]} className={styles.backlink} href="/">
        back
      </Link>
    </div>
  );
};

export default About;
