// code/ig-clone/ig-clone-next/src/app/user/[handle]/page.tsx
"use client";

import { useEffect, useState } from "react";
import ProfileService from "@/services/ProfileService";
import PostService from "@/services/PostService";
import NotInstagramLogo from "@/components/NotInstagramLogo";
import Profile from "@/components/Profile";
import XIcon from "@/components/icons/XIcon";
import styles from "./ProfilePage.module.css";
import Link from "next/link";

const ProfilePage = ({ params }: { params: { handle: string } }) => {
  params.handle = decodeURIComponent(params.handle);
  const [username, setUsername] = useState("");
  const [profileImageSource, setProfileImageSource] = useState("");
  const [caption, setCaption] = useState("");
  const [images, setImages] = useState<string[]>([]);

  useEffect(() => {
    ProfileService.getByHandle(params.handle).then((user) => {
      setUsername(user!.username);
      setProfileImageSource(user!.profileImageSource);
      setCaption(user!.caption);
    });

    PostService.getByUserHandle(params.handle).then((posts) => {
      setImages(posts.map((p) => p.mediaSource));
    });
  });

  return (
    <>
      <header className={styles.profileHeader}>
        <Link href="/">
          <NotInstagramLogo />
        </Link>
        <Link href="/">
          <XIcon />
        </Link>
      </header>

      <div id={styles.profileContainer}>
        <Profile
          username={username}
          handle={params.handle}
          profileImageSource={profileImageSource}
          caption={caption}
          createdAt={new Date()}
          images={images}
        />
      </div>
    </>
  );
};

export default ProfilePage;

// code/ig-clone/ig-clone-nuxt/pages/user/[handle].vue
<script setup>
const route = useRoute();
const handle = route.params.handle;
</script>

<template>
  <header>
    <NuxtLink :to="{ name: 'index' }">
      <NotInstagramLogo />
    </NuxtLink>
    <NuxtLink :to="{ name: 'index' }">
      <IconsXIcon />
    </NuxtLink>
  </header>

  <div id="profileContainer">
    <Profile
      :username="username"
      :handle="$route.params.handle"
      :profileImageSource="profileImageSource"
      :caption="caption"
      :createdAt="new Date()"
      :images="images"
    />
  </div>
</template>

<script>
import { useRoute } from "vue-router";
import ProfileService from "@/services/ProfileService";
import PostService from "@/services/PostService";

export default {
  name: "ProfileView",
  data() {
    return {
      username: "",
      handle: useRoute().params.handle,
      profileImageSource: "",
      caption: "",
      images: [],
    };
  },
  mounted() {
    ProfileService.getByHandle(this.handle).then((user) => {
      this.username = user.username;
      this.profileImageSource = user.profileImageSource;
      this.caption = user.caption;
    });
    PostService.getByUserHandle(this.handle).then(
      (posts) => (this.images = posts.map((p) => p.mediaSource))
    );
  },
};
</script>

<style scoped>
header {
  display: flex;
  justify-content: space-between;
  align-items: center;
  margin: 32px 16px;
}

header a {
  color: inherit;
  text-decoration: inherit;
}

#profileContainer {
  margin: 8px 16px;
}
</style>
