// code/ig-clone/ig-clone-nuxt/pages/about.vue
<template>
  <div id="AboutView">
    <NuxtLink id="top-backlink" class="backlink" :to="{ name: 'index' }">
      back
    </NuxtLink>

    <p class="cursive">This is</p>
    <NotInstagramLogo />
    <img class="transparent logo" src="~/assets/logo.svg" alt="" width="40%" />

    <p class="cursive">created by</p>
    <p class="cursive big">Andreas Nicklaus</p>
    <div id="socials">
      <p>
        <a href="https://github.com/andreasnicklaus" target="_blank">
          <img class="transparent" src="~/assets/github.svg" width="29" />
          @andreasnicklaus
        </a>
      </p>
      <p>
        <a href="https://www.linkedin.com/in/andreasnicklaus/" target="_blank">
          <img class="transparent" src="~/assets/linkedin.svg" width="29" />
          @andreasnicklaus
        </a>
      </p>
      <p>
        <a href="mailto:an067@hdm-stuttgart.de">
          <IconsSendIcon />
          an067@hdm-stuttgart.de
        </a>
      </p>
    </div>

    <InfoBlock title="What is this?">
      This project is part of the master thesis by Andreas Nicklaus with a
      working title. The following are just placholder texts.
    </InfoBlock>
    <InfoBlock title="Placeholder 1">
      Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod
      tempor incididunt ut labore et dolore magna aliqua. Elementum curabitur
      vitae nunc sed velit. Sagittis vitae et leo duis. Facilisi morbi tempus
      iaculis urna id volutpat lacus. Pellentesque id nibh tortor id aliquet
      lectus. Nisi quis eleifend quam adipiscing. Convallis a cras semper auctor
      neque vitae tempus quam. Pulvinar neque laoreet suspendisse interdum
      consectetur libero id faucibus. Facilisis sed odio morbi quis. Porttitor
      massa id neque aliquam vestibulum morbi blandit cursus. Lacus vestibulum
      sed arcu non odio euismod lacinia at. Sagittis eu volutpat odio facilisis
      mauris sit amet. Felis eget velit aliquet sagittis id consectetur purus.
      Sapien pellentesque habitant morbi tristique. Faucibus purus in massa
      tempor nec feugiat nisl. Lacus sed viverra tellus in hac. Mauris
      pellentesque pulvinar pellentesque habitant morbi tristique senectus.
      Rhoncus urna neque viverra justo nec. Amet cursus sit amet dictum sit amet
      justo donec enim. Sed libero enim sed faucibus turpis in.
    </InfoBlock>
    <InfoBlock title="Placeholder 2">
      Pellentesque diam volutpat commodo sed egestas egestas fringilla
      phasellus. Vulputate odio ut enim blandit. A condimentum vitae sapien
      pellentesque. Eu feugiat pretium nibh ipsum consequat nisl vel pretium.
      Feugiat nibh sed pulvinar proin gravida. Arcu non sodales neque sodales ut
      etiam sit amet. Amet risus nullam eget felis eget nunc lobortis. Diam vel
      quam elementum pulvinar etiam non quam lacus. Tincidunt id aliquet risus
      feugiat. Curabitur gravida arcu ac tortor dignissim convallis aenean. Cras
      fermentum odio eu feugiat pretium. Lacinia quis vel eros donec ac odio
      tempor. Eu turpis egestas pretium aenean pharetra.
    </InfoBlock>
    <InfoBlock title="Placeholder 3">
      Nec feugiat nisl pretium fusce. Sagittis id consectetur purus ut faucibus
      pulvinar elementum integer. Fusce id velit ut tortor. Enim blandit
      volutpat maecenas volutpat blandit aliquam etiam erat. Morbi quis commodo
      odio aenean sed adipiscing. Ut consequat semper viverra nam. Quisque
      egestas diam in arcu cursus euismod quis. Nec feugiat in fermentum posuere
      urna nec tincidunt. Ut lectus arcu bibendum at varius vel pharetra vel
      turpis. Tincidunt id aliquet risus feugiat. Id donec ultrices tincidunt
      arcu non sodales neque sodales. Vitae justo eget magna fermentum iaculis
      eu. Pellentesque habitant morbi tristique senectus et netus et. Sit amet
      consectetur adipiscing elit ut aliquam purus.
    </InfoBlock>
    <InfoBlock title="Placeholder 4">
      Ullamcorper malesuada proin libero nunc. Netus et malesuada fames ac
      turpis egestas. Aenean vel elit scelerisque mauris pellentesque pulvinar
      pellentesque. In iaculis nunc sed augue lacus viverra vitae congue.
      Pharetra sit amet aliquam id diam maecenas ultricies mi. Feugiat in
      fermentum posuere urna nec tincidunt praesent. Sollicitudin ac orci
      phasellus egestas tellus rutrum tellus pellentesque. Cursus vitae congue
      mauris rhoncus aenean vel elit scelerisque mauris. Fringilla phasellus
      faucibus scelerisque eleifend donec pretium vulputate sapien nec. Cursus
      eget nunc scelerisque viverra mauris in aliquam. Tellus orci ac auctor
      augue mauris. Ac orci phasellus egestas tellus rutrum tellus pellentesque
      eu. Consequat semper viverra nam libero justo laoreet sit amet. Mauris
      cursus mattis molestie a. Risus commodo viverra maecenas accumsan. Pretium
      lectus quam id leo in vitae turpis. Viverra tellus in hac habitasse platea
      dictumst. Cras pulvinar mattis nunc sed blandit libero volutpat. Ut
      faucibus pulvinar elementum integer enim neque volutpat. Orci a
      scelerisque purus semper eget duis at.
    </InfoBlock>
    <InfoBlock title="Placeholder 5">
      Adipiscing elit pellentesque habitant morbi tristique. Nulla at volutpat
      diam ut venenatis tellus in metus vulputate. Tortor consequat id porta
      nibh venenatis cras. Hac habitasse platea dictumst vestibulum. Arcu cursus
      vitae congue mauris rhoncus aenean vel elit. Erat pellentesque adipiscing
      commodo elit. Odio ut enim blandit volutpat maecenas volutpat blandit
      aliquam etiam. Semper viverra nam libero justo laoreet sit amet cursus.
      Semper eget duis at tellus at urna condimentum mattis pellentesque. Sed
      cras ornare arcu dui vivamus arcu felis. Vitae tortor condimentum lacinia
      quis vel eros donec ac. Vitae aliquet nec ullamcorper sit amet risus
      nullam. Pharetra massa massa ultricies mi. Cursus eget nunc scelerisque
      viverra mauris in aliquam sem fringilla. In massa tempor nec feugiat nisl
      pretium. Ultrices eros in cursus turpis massa tincidunt dui ut. Integer
      quis auctor elit sed. Ultricies integer quis auctor elit. Ridiculus mus
      mauris vitae ultricies leo integer malesuada nunc vel.
    </InfoBlock>
    <RouterLink id="bottom-backlink" class="backlink" :to="{ name: 'index' }">
      back
    </RouterLink>
  </div>
</template>

<style scoped>
#AboutView {
  display: flex;
  flex-direction: column;
  align-items: center;
  padding: 64px 32px;
}

.backlink {
  font-size: 14px;
  color: #adadad;
}

#top-backlink {
  margin-bottom: 64px;
}
#bottom-backlink {
  margin-top: 64px;
}

.cursive {
  font-family: "Kaushan Script", sans-serif;
  margin: 0;
}

.big {
  font-size: 24px;
}

.logo {
  margin: 16px 0 64px;
}

#socials {
  margin: 16px 0 64px;
}

#socials a {
  color: #dd458c;
  display: flex;
  align-items: center;
}

#socials img {
  margin-right: 16px;
}
</style>

// code/ig-clone/ig-clone-react/src/pages/About.js
import { Link } from "react-router-dom"
import styles from "./About.module.css"
import NotInstagramLogo from "src/components/NotInstagramLogo"
import SendIcon from "src/components/icons/SendIcon"
import Logo from "src/assets/logo.svg"
import Github from "src/assets/github.svg"
import LinkedIn from "src/assets/linkedin.svg"
import InfoBlock from "src/components/InfoBlock"

const About = () => {
  return <div id={styles.AboutView} >
    <Link id={styles["top-backlink"]} className={styles.backlink} to="/">
      back
    </Link>

    <p className={styles.cursive}>This is</p>
    <NotInstagramLogo />
    <img className={styles.logo + ' transparent'} src={Logo} alt="" width="40%" />

    <p className={styles.cursive}>created by</p>
    <p className={{ ...styles.cursive, ...styles.big }}>Andreas Nicklaus</p>
    <div id={styles.socials}>
      <p>
        <a href="https://github.com/andreasnicklaus" target="_blank">
          <img className="transparent" src={Github} width="29" />
          @andreasnicklaus
        </a>
      </p>
      <p>
        <a href="https://www.linkedin.com/in/andreasnicklaus/" target="_blank">
          <img className="transparent" src={LinkedIn} width="29" />
          @andreasnicklaus
        </a>
      </p>
      <p>
        <a href="mailto:an067@hdm-stuttgart.de">
          <SendIcon />
          an067@hdm-stuttgart.de
        </a>
      </p>
    </div>

    <InfoBlock title="What is this?">
      This project is part of the master thesis by Andreas Nicklaus with a
      working title. The following are just placholder texts.
    </InfoBlock>
    <InfoBlock title="Placeholder 1">
      Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod
      tempor incididunt ut labore et dolore magna aliqua. Elementum curabitur
      vitae nunc sed velit. Sagittis vitae et leo duis. Facilisi morbi tempus
      iaculis urna id volutpat lacus. Pellentesque id nibh tortor id aliquet
      lectus. Nisi quis eleifend quam adipiscing. Convallis a cras semper auctor
      neque vitae tempus quam. Pulvinar neque laoreet suspendisse interdum
      consectetur libero id faucibus. Facilisis sed odio morbi quis. Porttitor
      massa id neque aliquam vestibulum morbi blandit cursus. Lacus vestibulum
      sed arcu non odio euismod lacinia at. Sagittis eu volutpat odio facilisis
      mauris sit amet. Felis eget velit aliquet sagittis id consectetur purus.
      Sapien pellentesque habitant morbi tristique. Faucibus purus in massa
      tempor nec feugiat nisl. Lacus sed viverra tellus in hac. Mauris
      pellentesque pulvinar pellentesque habitant morbi tristique senectus.
      Rhoncus urna neque viverra justo nec. Amet cursus sit amet dictum sit amet
      justo donec enim. Sed libero enim sed faucibus turpis in.
    </InfoBlock>
    <InfoBlock title="Placeholder 2">
      Pellentesque diam volutpat commodo sed egestas egestas fringilla
      phasellus. Vulputate odio ut enim blandit. A condimentum vitae sapien
      pellentesque. Eu feugiat pretium nibh ipsum consequat nisl vel pretium.
      Feugiat nibh sed pulvinar proin gravida. Arcu non sodales neque sodales ut
      etiam sit amet. Amet risus nullam eget felis eget nunc lobortis. Diam vel
      quam elementum pulvinar etiam non quam lacus. Tincidunt id aliquet risus
      feugiat. Curabitur gravida arcu ac tortor dignissim convallis aenean. Cras
      fermentum odio eu feugiat pretium. Lacinia quis vel eros donec ac odio
      tempor. Eu turpis egestas pretium aenean pharetra.
    </InfoBlock>
    <InfoBlock title="Placeholder 3">
      Nec feugiat nisl pretium fusce. Sagittis id consectetur purus ut faucibus
      pulvinar elementum integer. Fusce id velit ut tortor. Enim blandit
      volutpat maecenas volutpat blandit aliquam etiam erat. Morbi quis commodo
      odio aenean sed adipiscing. Ut consequat semper viverra nam. Quisque
      egestas diam in arcu cursus euismod quis. Nec feugiat in fermentum posuere
      urna nec tincidunt. Ut lectus arcu bibendum at varius vel pharetra vel
      turpis. Tincidunt id aliquet risus feugiat. Id donec ultrices tincidunt
      arcu non sodales neque sodales. Vitae justo eget magna fermentum iaculis
      eu. Pellentesque habitant morbi tristique senectus et netus et. Sit amet
      consectetur adipiscing elit ut aliquam purus.
    </InfoBlock>
    <InfoBlock title="Placeholder 4">
      Ullamcorper malesuada proin libero nunc. Netus et malesuada fames ac
      turpis egestas. Aenean vel elit scelerisque mauris pellentesque pulvinar
      pellentesque. In iaculis nunc sed augue lacus viverra vitae congue.
      Pharetra sit amet aliquam id diam maecenas ultricies mi. Feugiat in
      fermentum posuere urna nec tincidunt praesent. Sollicitudin ac orci
      phasellus egestas tellus rutrum tellus pellentesque. Cursus vitae congue
      mauris rhoncus aenean vel elit scelerisque mauris. Fringilla phasellus
      faucibus scelerisque eleifend donec pretium vulputate sapien nec. Cursus
      eget nunc scelerisque viverra mauris in aliquam. Tellus orci ac auctor
      augue mauris. Ac orci phasellus egestas tellus rutrum tellus pellentesque
      eu. Consequat semper viverra nam libero justo laoreet sit amet. Mauris
      cursus mattis molestie a. Risus commodo viverra maecenas accumsan. Pretium
      lectus quam id leo in vitae turpis. Viverra tellus in hac habitasse platea
      dictumst. Cras pulvinar mattis nunc sed blandit libero volutpat. Ut
      faucibus pulvinar elementum integer enim neque volutpat. Orci a
      scelerisque purus semper eget duis at.
    </InfoBlock>
    <InfoBlock title="Placeholder 5">
      Adipiscing elit pellentesque habitant morbi tristique. Nulla at volutpat
      diam ut venenatis tellus in metus vulputate. Tortor consequat id porta
      nibh venenatis cras. Hac habitasse platea dictumst vestibulum. Arcu cursus
      vitae congue mauris rhoncus aenean vel elit. Erat pellentesque adipiscing
      commodo elit. Odio ut enim blandit volutpat maecenas volutpat blandit
      aliquam etiam. Semper viverra nam libero justo laoreet sit amet cursus.
      Semper eget duis at tellus at urna condimentum mattis pellentesque. Sed
      cras ornare arcu dui vivamus arcu felis. Vitae tortor condimentum lacinia
      quis vel eros donec ac. Vitae aliquet nec ullamcorper sit amet risus
      nullam. Pharetra massa massa ultricies mi. Cursus eget nunc scelerisque
      viverra mauris in aliquam sem fringilla. In massa tempor nec feugiat nisl
      pretium. Ultrices eros in cursus turpis massa tincidunt dui ut. Integer
      quis auctor elit sed. Ultricies integer quis auctor elit. Ridiculus mus
      mauris vitae ultricies leo integer malesuada nunc vel.
    </InfoBlock>
    <Link id={styles["bottom-backlink"]} className={styles.backlink} to="/">
      back
    </Link>
  </div >
}

export default About
