// code/ig-clone/ig-clone-angular/src/app/feed/feed.component.ts
import { PostService } from './../../services/PostService';
import { ProfileService } from './../../services/ProfileService';
import { Component } from '@angular/core';
import { LogoHeaderComponent } from '../components/logo-header/logo-header.component';
import { ProfileListComponent } from '../components/profile-list/profile-list.component';
import { PostListComponent } from '../components/post-list/post-list.component';
import { RouterLink } from '@angular/router';
import { InfoIconComponent } from '../components/icons/info-icon/info-icon.component';

@Component({
  selector: 'app-feed',
  standalone: true,
  imports: [LogoHeaderComponent, ProfileListComponent, PostListComponent, RouterLink, InfoIconComponent],
  templateUrl: './feed.component.html',
  styleUrl: './feed.component.css'
})
export class FeedComponent {
  profiles: Array<Object> = [];
  posts: Array<Object> = [];

  constructor(private profileService: ProfileService, private postService: PostService) {
    profileService.getAll().then(p => this.profiles = p);
    postService.getAll().then(p => this.posts = p);
  }
}

<app-logo-header />

<app-profile-list [profiles]="profiles" />
<app-post-list [posts]="posts" />
<footer>
  <hr />
  <a [routerLink]="['/about']" routerLinkActive="router-link-active">
    <app-info-icon /> <span> Info </span>
  </a>
</footer>

// code/ig-clone/ig-clone-react/src/pages/Feed.js
import { useState } from 'react';

import ProfileList from "src/components/ProfileList"
import LogoHeader from "../components/LogoHeader"
import ProfileService from "src/services/ProfileService"
import PostService from "src/services/PostService"
import PostList from 'src/components/PostList';
import { Link } from 'react-router-dom';
import InfoIcon from 'src/components/icons/InfoIcon';
import styles from "./Feed.module.css"
const Feed = () => {
  let [profiles, setProfiles] = useState([])
  ProfileService.getAll().then(p => setProfiles(p))

  let [posts, setPosts] = useState([])
  PostService.getAll().then(p => setPosts(p))

  return <>
    <LogoHeader />
    <ProfileList profiles={profiles} />
    <PostList posts={posts} />
    <footer>
      <hr />
      <Link to="/about"> <InfoIcon /> Info </Link>
    </footer>
  </>
}

export default Feed
